### Get all contacts
GET http://localhost:8080/contacts

### Get single contact by ID
GET http://localhost:8080/contacts/6a4163a52251a3e9bfdb4bf5

### Create a new contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Adonai",
  "lastName": "Villalobos",
  "email": "adonai@email.com",
  "favoriteColor": "blue",
  "birthday": "1995-01-01"
}

### Update a contact
PUT http://localhost:8080/contacts/6a4163a52251a3e9bfdb4bf5
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.updated@email.com",
  "favoriteColor": "purple",
  "birthday": "1985-03-22"
}

### Delete a contact
DELETE http://localhost:8080/contacts/6a4163a52251a3e9bfdb4bf5